### ISSUE TITLE
QSyncthingTray force KDE 5.6.4 Plasmashell to fill out constantly RAM memory, including SWAP memory, if active

### ISSUE THREAD

**Issue by Getron** [sieren/QSyncthingTray#123] opened 2016-05-30 02:28 UTC
Hi

Today i have seen strange filling up my 16GB RAM, in couple of minutes after restart the entire 16 GB of RAM plus the entire Swap size of 20 GB, in jkust couple of minutes.

I have checked, what app do this, and it is Plasmashell on my NetRunner KDE rolling release.

Then i have started to shut down every app i have run on background, starting from Tray, and guess what, the QSyncthingTray is doing this problem.And it is localy connected with my localy installed Syncthing, on local machine.

I have checked and restart the machine couple of times, let the QSyncthingTray to work, and looked at the filling of RAM memory. The RAM does fill up from second to second about 100MB/s, and, if i close the QSyncthingTray, Plasmashell consumption and RAM stay like it is, but, if i started up again QSyncthingTray again, it fill up constantly further the RAM.

Interesting is, that the RAM fills the Plasmashell, and not the QSyncthingTray itself. and it fill up, just if working, if the icon is rotating. If i click on Pause Syncthing, the RAM filling it doesn't fill anmore.

Perhaps, the problem is just in case of syncing, or, maybe in case of scanning. I thing, scanning force this problem, because, i have just one folder who has many small files (and is about 55 GB big), and it scanns, and then, when scanns (not syncing) the problem of RAM filling apear.

And the i7 CPU is goind on the marc of 80% (all 8 cores), it goes crazy. If QSyncthingTray is closed, all is on normal, the CPU goes down to under 10%. RAM stays filled up (maybe goes down little bit, after couple of seconds or a minute), but not further filling, until i restart the QSyncthingTray. If i restarted it, entire machine goes crazy: 8 core i7 CPU on 80%, and RAM starts to fill up, aproximatelly with speed of 100MB/s.

i can attach a video on my server, to see the problem.

**Comment by sieren** [comment] 2016-05-30 07:40
Hey @Getron 

unfortunately that's a known bug with Plasmashell:
https://github.com/sieren/QSyncthingTray/issues/106

I deployed a fix earlier this year, but it's only a workaround (since the underlying issue is in Qt).
I can recommend switching off the animated Icon for now.

Can you try it without animation activated and tell me how that works?

Seems like I need to add a `Known Issues` list to the front page.

Cheers and thanks for the detailed report!

**Comment by sieren** [comment] 2016-05-30 09:44
I'll try to come up with some example code to reproduce this and will file a bug report with Qt/KDE

**Comment by Getron** [comment] 2016-05-30 13:24
Hi @sieren i have tested without the animation to, but, it is not the animation that do the CPU crazy, somthing else it force the 8 core i7 CPU to go 80%.

If i quit the QSyncthingTray, the CPU goes to normal, about 5-10%.

The RAM fills up just in case of scanning a big folder with many small files. For example, i have a folder where i have copy of all my web sites files, about 55GB, and if scanning RAM goes up filling, but not if syncing the same folder.

In my Arch Distro NetRunner rolling KDE release, the KDE doesn't crash, but it fills up entire RAM, Swap, and CPU if scanning big folder with small files.

I hope we can fix this problem somehow.

Thank you Matt for investigating on this.

**Comment by Getron** [comment] 2016-05-30 13:39
p.s: now it has finished to syncing this big folder, and the CPU goes to normal, about 5-10%, but RAM stays filled up, maybe just move a GB down or so.

On scanning, the CPU was about 80%
On syncing, CPU was about 40%
On idle, CPU is 5-10%

**Comment by sieren** [comment] 2016-05-30 17:35
I have a suspicion - in case you're compiling QST on your own, there's a clean-up branch I'm adding more stuff on top: https://github.com/sieren/QSyncthingTray/pull/124

But right now it seems like for every potential bug I uncover on KDE 5, there's a new one. For some reason the Menu that pops up never gets updated properly after initialisation. (Setting a new title to the actions, like connection-status-info, never reaches KDE5 - works fine on all other platforms).

I'll try and get some more work done on this in the next few days, but having someone on board with more Qt and KDE expertise would certainly help.

**Comment by Getron** [comment] 2016-05-30 21:54
@sieren What suspicion?

I have searched for config file of QSyncthingTray, and about a hour later, i have found, it has the name "sieren"
Can you please change this to name of app? Nobody can find it easely, if you take your nick for main config folder, and, i have seen this folder with your name, or nick, and, because i known your nick here, i have preposed, it can this folder be what i search for. But, someone, who does known, can mainly not find the right config dir of this app.

Please, change this, and other things in code, where is "sieren" as funktion, or such. Better use somthing as symbolic, but not own nick name.

**Comment by sieren** [comment] 2016-05-31 08:02
Yeah, that's from back in the days. Every platform handles that differently and Qt specified it as a "company" identifier.. I'll move that to QST later.

**Comment by Getron** [comment] 2016-06-23 15:55
@sieren I think, i found what cause the problem to fill up entire RAM memory, constantly: it is the animated tray icon.

If the animated icon is rotating, the RAM memory goes crazy, ca. 100 MB/s it fills up, constantly.

But, if i disable animation, the memory stay fixed (but not empty it, just stay constant, like it should be)

I think, it is somwhere problem with animation of icon, and the new KDE.

Maybe you can check this out?

**Comment by sieren** [comment] 2016-06-23 19:16
This is kind of what I suspected in the first place. 
I filed a preliminary fix for this as part of https://github.com/sieren/QSyncthingTray/issues/106 but there's no work-around for the rotating icon right now as its a memory leak in Qt/Plasma.

**Closed** 2016-10-26 15:36 UTC
Labels: Known Issue, Qt, wontfix
