### ISSUE TITLE
Zoom level not working.

### ISSUE THREAD

**Issue by BethAr** [sieren/QSyncthingTray#100] opened 2016-03-26 20:54 UTC
Hey there,

The zoom option in preferences makes no difference in the webview, no matter what value I set it to. I'm using QSyncthingTray on Manjaro with KDE.

Thank you.

**Comment by sieren** [comment] 2016-03-28 20:33
Hey,
which version of Qt is QST compiled with?
Looking at the Qt Bugreporter I see this:
https://bugreports.qt.io/browse/QTBUG-51992
https://bugreports.qt.io/browse/QTBUG-51851

Any chance it's Qt 5.6?

**Comment by BethAr** [comment] 2016-03-29 11:59
The version of Qt installed is 5.5.1-10.

I've noticed that they are speaking about setting the zoom level before launching, are we supposed to be able to set it afterwards? I get no reaction from Ctrl+ / Ctrl-.

**Comment by mfk-ableton** [comment] 2016-03-29 12:00
I have never tried the ctrl-commands, there is however a zoom-level field in the settings.

**Comment by sieren** [comment] 2016-03-29 12:01
I have never tried the ctrl-commands, there is however a zoom-level field in the settings.

**Comment by BethAr** [comment] 2016-03-29 12:57
Yes, the zoom setting is what I'm reporting about, I'm just adding that the Ctrl commands, if they should work, don't work also.

**Comment by BethAr** [comment] 2016-03-31 13:58
I've upgraded to Qt 5.6.1, will see if the problem persists.

**Comment by BethAr** [comment] 2016-03-31 14:10
The problem persists after the upgrade.

**Comment by sieren** [comment] 2016-04-02 11:25
![screen shot 2016-04-02 at 13 24 10](https://cloud.githubusercontent.com/assets/5174440/14225991/60ff71ae-f8d6-11e5-851a-70650d393e12.png)
![screen shot 2016-04-02 at 13 24 00](https://cloud.githubusercontent.com/assets/5174440/14225992/6123725c-f8d6-11e5-96e4-ee3e3ed98a08.png)

Same here, unable to reproduce on Manjaro. Seems to work on my end?

**Comment by BethAr** [comment] 2016-04-03 07:40
I've found the problem.

If you change the preferences with the main window closed the setting is simply ignored. I hadn't tried to change it like in your screenshots, with the window open, so it never worked. If I open the window as you did, it works normally when I adjust the settings.

**Comment by sieren** [comment] 2016-04-03 09:33
Ohhh, that's clearly a bug. Will investigate. By Main window you mean the Syncthing UI right?

**Comment by sieren** [comment] 2016-04-03 09:52
Deployed a fix to master. Thanks for the report. This will be resolved in the next version.

**Closed by sieren** 2016-04-03 09:52 UTC
Labels: bug

**Comment by BethAr** [comment] 2016-04-04 07:43
Sorry for the delay, but I did mean the main Syncthing UI.

Thanks, I will wait eagerly for the fix!
